namespace Shelter.Core.Enums
{
    public enum Race
    {
        Bulldog,
        Dalmatian,
        Mastiff,
        Rottweiler,
        Scrub,
        Boxer,
        York,
        ShihTzu,
        AlaskanHusky,
        Spaniel,
        Beagle,
        Chihuahua,
        ChowChow,
        Corgi,
        BengalCat,
        BritishCat,
        MaineCoonCat,
        NorwegianForestCat,
        PersianCat,
        RagdollCat,
        SphynxCat,
        AlleyCat,
        GuineaPig,
        Hamster,
        Chinchilla,
        Rabbit,
        Turtle,
        Goldfish,
    }
}
